# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 96deea65a73d1c1b471e10e1c3acd7a192695c69554a0f0d5f92b768c0fc3f4e744933a64aeb2ca57afe39ea196c4b597019cbb9aeb227ff812970f41769458b

test:
  secret_key_base: 4f4178ac90daefcf83febc346b65285aa0d89bfe826e3aceae2375fce49528da2298834334043d2c02cc54cd44c829feac0e01747bedcbec491ee5aede6c7cda

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
